"""Paramètres smart_money (ARCH-05) — extrait de smart_money.py."""
from __future__ import annotations

from typing import Any, Dict, List

PARAM_SPACE: Dict[str, List] = {
    'swing_len': [2, 3, 5],
    'eq_tol_atr': [0.15, 0.25, 0.4],
    'disp_body_atr': [1.0, 1.3, 1.6],
    'min_rr': [1.0, 1.2, 1.5],
    'min_gain_pct': [0.4, 0.8, 1.2],
    'sl_buffer_atr': [0.15, 0.25, 0.5],
    'ema_filter_len': [0, 100, 200],
    'choch_exit': [True, False],
    'use_breakers': [True, False],
    'use_void_targets': [True, False],
    'htf_filter': ['off', 'soft', 'strict'],
    'kz_bonus': [True, False],
    'amd_bonus': [True, False],
    'vp_confluence': [True, False],
    'use_rejection_blocks': [True, False],
    'time_stop_bars': [0, 12, 16, 24],
    'use_trailing': [True, False],
    'trail_mult': [2.0, 2.5, 3.5],
    'size_by_confluence': [True, False],
    'size_conf_slope': [2.0, 3.0, 4.0],
    'ext_structure_filter': [True, False],
    'tp_measured_move': [True, False],
    'inv_fvg_bonus': [True, False],
    'chop_filter_max': [0.0, 61.8],
    'candle_bonus': [True, False],
    'smt_bonus': [True, False],
    'smt_filter': [True, False],
    'smt_at_origin': [True, False],
    'require_inducement': [True, False],
    'judas_bonus': [True, False],
    'judas_filter': [True, False],
    'tp_std_dev': [True, False],
    'use_bpr': [True, False],
    'sb_bonus': [True, False],
    'sb_filter': [True, False],
    'pd_mode': ['swing', 'ipda'],
    'ipda_lookback': [20, 40, 60],
    'mitigation_mode': ['off', 'exclude', 'penalize'],
    'amd_session_anchored': [True, False],
    'use_calendar_liquidity': [False, 'targets', 'sweeps', True],
}

FIXED_PARAMS: Dict[str, Any] = {
    'swing_len': 3,
    'eq_tol_atr': 0.25,
    'disp_body_atr': 1.3,
    'ob_lookback': 5,
    'fvg_min_atr': 0.2,
    'min_gain_pct': 0.4,
    'min_rr': 1.2,
    'sl_buffer_atr': 0.25,
    'tp_rr_fallback': 2.0,
    'tp_front_run_atr': 0.1,
    'vol_confluence': 1.2,
    'allow_counter_trend': False,
    'use_breakers': False,
    'use_void_targets': True,
    'tl_tol_atr': 0.3,
    'htf_filter': 'soft',
    'htf_mult': 4,
    'use_rejection_blocks': False,
    'rb_wick_atr': 0.5,
    'vp_confluence': False,
    'vp_targets': False,
    'vp_lookback': 240,
    'vp_bins': 40,
    'kz_bonus': False,
    'kz_filter': False,
    'amd_bonus': False,
    'amd_bars': 12,
    'amd_range_atr': 2.0,
    'min_score': 0.0,
    'ema_filter_len': 200,
    'choch_exit': False,
    'max_window': 3000,
    'ob_max_age': 250,
    'pool_max_age': 500,
    'choch_guard_bars': 5,
    'time_stop_bars': 0,
    'use_trailing': False,
    'trail_mult': 2.5,
    'ts_profit_r': 1.0,
    'size_by_confluence': False,
    'size_conf_slope': 3.0,
    'size_conf_center': 0.83,
    'ext_structure_filter': False,
    'ext_swing_len': 8,
    'tp_measured_move': False,
    'inv_fvg_bonus': False,
    'chop_filter_max': 0.0,
    'chop_len': 14,
    'candle_bonus': False,
    'smt_correlate_path': '',
    'smt_lookback': 20,
    'smt_bonus': False,
    'smt_filter': False,
    'smt_conf': 0.05,
    'smt_at_origin': False,
    'require_inducement': False,
    'inducement_lookback': 12,
    'judas_bonus': False,
    'judas_filter': False,
    'judas_open_hour': 8,
    'judas_window': 3,
    'judas_lookback': 12,
    'tp_std_dev': False,
    'use_bpr': False,
    'sb_bonus': False,
    'sb_filter': False,
    'pd_mode': 'swing',
    'ipda_lookback': 40,
    'mitigation_mode': 'off',
    'amd_session_anchored': False,
    'use_calendar_liquidity': False,
}
